### ISSUE TITLE
Integrating into other projects?

### ISSUE THREAD

**Issue by TheDevMinerTV** [ttscoff/na#9]
Hi @ttscoff !

First of all, this here is a very good todo planner. :+1:

I wanted to ask if I could integrate this little project into @vergissberlin's bashlib.
This is a wonderful collection of good programs.

- Tobias aka. TheDevMinerTV

**Comment by ttscoff** [comment]
Sure, with attribution.

-Brett

**Comment by TheDevMinerTV** [comment]
Yeah, you get full credit!
Thanks for creating this piece of OSS!

- Tobias aka. TheDevMinerTV
